version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 20
    target-branch: main
